import type { ScanManifestEntry } from "./dynamo-scan-manifest.ts";

/** Manifest entries for Scan call sites that run under the rest/websocket/cron Lambda role. */
export const PRODUCTION_SCAN_MANIFEST: readonly ScanManifestEntry[] = [
  {
    file: "services/api/src/db/plane-storage-catalog.ts",
    tableExpr: "ctx.tables.schedules",
    count: 1,
    tables: ["Schedules"],
    runsUnderLambdaRole: true,
    why: "list all schedules for the catalog page; no secondary index over schedule scope.",
  },
  {
    file: "services/api/src/db/plane-storage-catalog.ts",
    tableExpr: "ctx.tables.repositories",
    count: 2,
    tables: ["Repositories"],
    runsUnderLambdaRole: true,
    why: "repository catalog hydrate-on-boot snapshot and the paginated repositories list API.",
  },
  {
    file: "services/api/src/db/plane-storage-catalog.ts",
    tableExpr: "ctx.tables.archives",
    count: 1,
    tables: ["Archives"],
    runsUnderLambdaRole: true,
    why: "archive catalog hydrate-on-boot snapshot; no owner index for a full listing.",
  },
  {
    file: "services/api/src/db/plane-storage-catalog.ts",
    tableExpr: "ctx.tables.hostInventories",
    count: 1,
    tables: ["HostInventories"],
    runsUnderLambdaRole: true,
    why: "host inventory catalog hydrate-on-boot snapshot.",
  },
  {
    file: "services/api/src/db/plane-storage-catalog-providers.ts",
    tableExpr: "tableName",
    count: 1,
    tables: ["Providers", "Commands"],
    runsUnderLambdaRole: true,
    why: "shared paginated-list helper (listCatalogTablePage) invoked for the Providers and Commands catalogs.",
  },
  {
    file: "services/api/src/db/plane-storage-catalog-providers.ts",
    tableExpr: "ctx.tables.providers",
    count: 1,
    tables: ["Providers"],
    runsUnderLambdaRole: true,
    why: "provider catalog hydrate-on-boot snapshot.",
  },
  {
    file: "services/api/src/db/plane-storage-catalog-providers.ts",
    tableExpr: "ctx.tables.commands",
    count: 1,
    tables: ["Commands"],
    runsUnderLambdaRole: true,
    why: "command catalog hydrate-on-boot snapshot.",
  },
  {
    file: "services/api/src/db/plane-storage-auth.ts",
    tableExpr: "ctx.tables.users",
    count: 1,
    tables: ["Users"],
    runsUnderLambdaRole: true,
    why: "list all local auth accounts; account management has no secondary index.",
  },
  {
    file: "services/api/src/db/plane-storage-workspaces.ts",
    tableExpr: "ctx.tables.workspacePools",
    count: 2,
    tables: ["WorkspacePools"],
    runsUnderLambdaRole: true,
    why: "workspace pool catalog hydrate-on-boot snapshot and listHostsDurable's scheduler read-model projection.",
  },
  {
    file: "services/api/src/db/plane-storage-workspaces.ts",
    tableExpr: "ctx.tables.workspaceSlots",
    count: 1,
    tables: ["WorkspaceSlots"],
    runsUnderLambdaRole: true,
    why: "workspace slot catalog hydrate-on-boot snapshot.",
  },
  {
    file: "services/api/src/db/plane-storage-usage.ts",
    tableExpr: "ctx.tables.sessionUsage",
    count: 1,
    tables: ["SessionUsage"],
    runsUnderLambdaRole: true,
    why: "session usage rollup listing; no secondary index over all usage records.",
  },
  {
    file: "services/api/src/db/plane-storage-provider-accounts.ts",
    tableExpr: "ctx.tables.providerAccounts",
    count: 1,
    tables: ["ProviderAccounts"],
    runsUnderLambdaRole: true,
    why: "provider account catalog hydrate-on-boot snapshot.",
  },
  {
    file: "services/api/src/db/ensure-session-drain-ledger.ts",
    tableExpr: "tables.sessions",
    count: 1,
    tables: ["Sessions"],
    runsUnderLambdaRole: true,
    why: "one-time session-drain-ledger backfill migration; Sessions Scan is already granted for the production list paths, so this is covered whichever driver (local bootstrap or deploy) runs it.",
  },
  {
    file: "services/api/src/db/plane-storage-sessions-worktrees.ts",
    tableExpr: "ctx.tables.worktrees",
    count: 2,
    tables: ["Worktrees"],
    runsUnderLambdaRole: true,
    why: "worktree catalog hydrate-on-boot snapshot and the paginated worktrees list API.",
  },
  {
    file: "services/api/src/db/ensure-session-priority-order.ts",
    tableExpr: "tables.sessions",
    count: 1,
    tables: ["Sessions"],
    runsUnderLambdaRole: true,
    why: "one-time session-priority-order backfill migration; Sessions Scan is already granted for the production list paths, covered whichever driver runs it.",
  },
  {
    file: "services/api/src/db/plane-storage-sessions-query.ts",
    tableExpr: "ctx.tables.sessions",
    count: 2,
    tables: ["Sessions"],
    runsUnderLambdaRole: true,
    why: "session catalog hydrate-on-boot snapshot and the by-repository session filter (no repository index).",
  },
  {
    file: "services/api/src/db/ensure-archive-retry-index.ts",
    tableExpr: "tables.archives",
    count: 1,
    tables: ["Archives"],
    runsUnderLambdaRole: true,
    why: "one-time archive-retry-index backfill migration; Archives Scan is already granted for the production list paths, covered whichever driver runs it.",
  },
  {
    file: "services/api/src/db/plane-storage-webhook-outbox.ts",
    tableExpr: "ctx.tables.webhookDeliveries",
    count: 1,
    tables: ["WebhookDeliveries"],
    runsUnderLambdaRole: true,
    why: "webhook delivery outbox listing for operator debugging; no secondary index.",
  },
  {
    file: "services/api/src/db/plane-storage-locks.ts",
    tableExpr: "ctx.tables.connections",
    count: 1,
    tables: ["Connections"],
    runsUnderLambdaRole: true,
    why: "connection catalog hydrate-on-boot snapshot.",
  },
  {
    file: "services/api/src/db/plane-storage-integrations.ts",
    tableExpr: "ctx.tables.integrations",
    count: 1,
    tables: ["Integrations"],
    runsUnderLambdaRole: true,
    why: "list all custom webhook integrations for the delete-guard reference check; single-digit rows, no index.",
  },
  {
    file: "services/api/src/db/plane-storage-session-drains.ts",
    tableExpr: "ctx.tables.sessionDrains",
    count: 2,
    tables: ["SessionDrains"],
    runsUnderLambdaRole: true,
    why: "session drain catalog snapshot and the cron reconciler's stuck-drain sweep.",
  },
];
