export const auditAppendFailureRequests = [
  [
    "POST",
    "/api/v1/sessions",
    {
      repositoryId: "repository-a",
      target: { commandId: "command-a" },
      prompt: "safe",
      timeout: 60,
    },
  ],
  ["POST", "/api/v1/sessions/session-a/cancel", {}],
  ["POST", "/api/v1/sessions/session-a/clone", {}],
  ["POST", "/api/v1/sessions/session-a/resume", {}],
  ["POST", "/api/v1/sessions/session-a/archive", {}],
  ["POST", "/api/v1/repositories", { name: "other", url: "https://example.test/other.git" }],
  ["PATCH", "/api/v1/repositories/repository-a", { name: "renamed" }],
  [
    "POST",
    "/api/v1/schedules",
    {
      repositoryId: "repository-a",
      name: "other",
      target: { commandId: "command-a" },
      cron: "* * * * *",
      timeout: 60,
      nextRunAt: "2026-08-10T00:00:00.000Z",
    },
  ],
  ["POST", "/api/v1/schedules/schedule-a/trigger", {}],
  ["PATCH", "/api/v1/schedules/schedule-a", { name: "renamed" }],
  ["DELETE", "/api/v1/schedules/schedule-a", {}],
  ["POST", "/api/v1/providers", { name: "other" }],
  ["PATCH", "/api/v1/providers/provider-a", { name: "renamed" }],
  ["POST", "/api/v1/provider-accounts", { providerId: "provider-a", label: "other" }],
  ["PATCH", "/api/v1/provider-accounts/account-a", { label: "renamed" }],
  ["POST", "/api/v1/commands", { name: "other", argv: ["tool"] }],
  ["PATCH", "/api/v1/commands/command-a", { name: "renamed" }],
  ["POST", "/api/v1/scheduler/assign", {}],
  ["POST", "/api/v1/scheduler/ack-deadlines", {}],
  ["POST", "/api/v1/scheduler/reclaim-stale", {}],
  ["POST", "/api/v1/scheduler/cron", {}],
  ["POST", "/api/v1/hosts/drain", { hostId: "host-a" }],
] as const;

export const durableMutationFailureCases = [
  [
    "POST",
    "/api/v1/repositories",
    { name: "other", url: "https://example.test/other.git" },
    "createRepositoryDurable",
    "repository:create",
  ],
  [
    "PATCH",
    "/api/v1/repositories/repository-a",
    { name: "other" },
    "updateRepositoryDurable",
    "repository:update",
  ],
  [
    "DELETE",
    "/api/v1/repositories/repository-a",
    {},
    "deleteRepositoryDurable",
    "repository:delete",
  ],
  [
    "POST",
    "/api/v1/schedules",
    {
      repositoryId: "repository-a",
      name: "other",
      target: { commandId: "command-a" },
      cron: "* * * * *",
      timeout: 60,
      nextRunAt: "2026-08-10T00:00:00.000Z",
    },
    "putScheduleDurable",
    "schedule:create",
  ],
  [
    "POST",
    "/api/v1/schedules/schedule-a/trigger",
    {},
    "triggerScheduleDurable",
    "schedule:trigger",
  ],
  [
    "PATCH",
    "/api/v1/schedules/schedule-a",
    { name: "other" },
    "updateScheduleDurable",
    "schedule:update",
  ],
  ["DELETE", "/api/v1/schedules/schedule-a", {}, "deleteScheduleDurable", "schedule:delete"],
  ["POST", "/api/v1/providers", { name: "other" }, "createProviderDurable", "provider:create"],
  [
    "PATCH",
    "/api/v1/providers/provider-a",
    { name: "other" },
    "updateProviderDurable",
    "provider:update",
  ],
  ["DELETE", "/api/v1/providers/provider-a", {}, "deleteProviderDurable", "provider:delete"],
  [
    "POST",
    "/api/v1/provider-accounts",
    { providerId: "provider-a", label: "other" },
    "createProviderAccountDurable",
    "provider-account:create",
  ],
  [
    "PATCH",
    "/api/v1/provider-accounts/account-a",
    { label: "other" },
    "updateProviderAccountDurable",
    "provider-account:update",
  ],
  [
    "DELETE",
    "/api/v1/provider-accounts/account-a",
    {},
    "deleteProviderAccountDurable",
    "provider-account:delete",
  ],
  [
    "DELETE",
    "/api/v1/provider-accounts/account-a/usage-limit",
    {},
    "clearProviderAccountUsageLimitDurable",
    "provider-account:clear-usage-limit",
  ],
  [
    "POST",
    "/api/v1/commands",
    { name: "other", argv: ["tool"] },
    "createCommandDurable",
    "command:create",
  ],
  [
    "PATCH",
    "/api/v1/commands/command-a",
    { name: "other" },
    "updateCommandDurable",
    "command:update",
  ],
  ["DELETE", "/api/v1/commands/command-a", {}, "deleteCommandDurable", "command:delete"],
  [
    "PUT",
    "/api/v1/hosts/host-a/inventory",
    { repositories: [], commandProfiles: {} },
    "putHostInventoryDurable",
    "host-inventory:update",
  ],
  [
    "DELETE",
    "/api/v1/hosts/host-a/inventory",
    {},
    "deleteHostInventoryDurable",
    "host-inventory:delete",
  ],
  [
    "POST",
    "/api/v1/sessions",
    {
      repositoryId: "repository-a",
      target: { commandId: "command-a" },
      prompt: "safe",
      timeout: 60,
    },
    "createSessionDurable",
    "session:create",
  ],
  ["POST", "/api/v1/sessions/session-a/cancel", {}, "cancelSessionDurable", "session:cancel"],
  ["POST", "/api/v1/sessions/session-a/resume", {}, "resumeSessionDurable", "session:resume"],
  ["POST", "/api/v1/scheduler/assign", {}, "assignQueuedDurable", "scheduler:assign"],
  [
    "POST",
    "/api/v1/scheduler/ack-deadlines",
    {},
    "enforceAckDeadlinesDurable",
    "scheduler:ack-deadlines",
  ],
  [
    "POST",
    "/api/v1/scheduler/reclaim-stale",
    {},
    "reclaimStaleHostsDurable",
    "scheduler:reclaim-stale",
  ],
  ["POST", "/api/v1/scheduler/cron", {}, "evaluateCronDurable", "scheduler:cron"],
] as const;
