/* eslint-disable max-lines -- admission validates the frozen workspace control frame. */
import { validateCreateSessionInput, type TargetRef } from "@auto-harness/shared";

import type { ControlPlaneState } from "./control-plane-state.ts";
import { hashString } from "./control-plane-state.ts";
import { resolveTargetDisplayNames } from "./control-plane-session-target-display-name.ts";
import type { SessionRecord } from "./db/types.ts";
import { repositoryAdmissionFailure } from "./control-plane-repository-admission-state.ts";

type ValidatedFields = Extract<
  ReturnType<typeof validateCreateSessionInput>,
  { ok: true }
>["value"];

/** Mirrors the outbound workspace scheduler guard, with protocol framing headroom. */
const MAX_WORKSPACE_ASSIGN_BYTES = 120 * 1024;

type WorkspaceAssignmentRoute = {
  commandId: string;
  providerId?: string;
  providerAccountId?: string;
  targetIndex: number;
  resolvedArgv: string[];
};

type WorkspaceAdmissionRoute = Omit<WorkspaceAssignmentRoute, "targetIndex" | "resolvedArgv">;

export type WorkspaceAssignmentFields = {
  workspacePoolId: string;
  setupProfileId?: string | undefined;
  workspaceSetupScript?: string | undefined;
  destroyWorkspaceAfter?: boolean | undefined;
  prompt: string;
  target: TargetRef;
  fallbacks: TargetRef[];
  timeout: number;
  metadata?: Record<string, unknown> | undefined;
};

function workspaceAdmissionRoutes(
  state: ControlPlaneState,
  workspacePoolId: string,
  target: TargetRef,
): WorkspaceAdmissionRoute[] {
  if ("commandId" in target) {
    const command = state.commands.get(target.commandId);
    if (!command) return [];
    const providerId = command.providerId ?? undefined;
    if (!providerId) return [{ commandId: command.id }];
    const accounts = [...state.providerAccounts.values()]
      .filter((account) => account.providerId === providerId)
      .map((account) => account.id);
    return (accounts.length ? accounts : ["x".repeat(512)]).map((providerAccountId) => ({
      commandId: command.id,
      providerId,
      providerAccountId,
    }));
  }

  const provider = state.providers.get(target.providerId);
  const routes: WorkspaceAdmissionRoute[] = [];
  // A new host may opt into the pool after this session is admitted. Its
  // provider default is the only command it can use without host config.
  if (provider?.defaultCommandId && state.commands.has(provider.defaultCommandId)) {
    routes.push({
      commandId: provider.defaultCommandId,
      providerId: target.providerId,
      providerAccountId: "x".repeat(512),
    });
  }
  for (const inventory of state.hostInventories.values()) {
    if (!inventory.workspacePools?.some((pool) => pool.workspacePoolId === workspacePoolId)) {
      continue;
    }
    for (const hostAccount of inventory.providerAccounts) {
      const account = state.providerAccounts.get(hostAccount.providerAccountId);
      if (account?.providerId !== target.providerId) continue;
      const commandId = hostAccount.commandId ?? provider?.defaultCommandId;
      if (!commandId || !state.commands.has(commandId)) continue;
      routes.push({ commandId, providerId: target.providerId, providerAccountId: account.id });
    }
  }
  return [
    ...new Map(
      routes.map((route) => [`${route.commandId}:${route.providerAccountId}`, route]),
    ).values(),
  ];
}

function workspaceAssignmentMessage(
  fields: WorkspaceAssignmentFields,
  setupScript: string | undefined,
  route: WorkspaceAssignmentRoute,
): Record<string, unknown> {
  return {
    type: "session:assign",
    // These opaque IDs are generated by Auto Harness. Reserve considerably
    // more than their UUID representation for the admission calculation.
    sessionId: "x".repeat(512),
    sessionType: "workspace",
    repositoryId: null,
    worktreeId: null,
    workspacePoolId: fields.workspacePoolId,
    workspaceSlotId: "x".repeat(512),
    ...(fields.setupProfileId ? { setupProfileId: fields.setupProfileId } : {}),
    ...(setupScript ? { setupScript } : {}),
    ...(fields.destroyWorkspaceAfter !== undefined
      ? { destroyWorkspaceAfter: fields.destroyWorkspaceAfter }
      : {}),
    // resolvedArgv is the only workspace execution input; do not duplicate an
    // untrusted prompt on the wire, including for appendPrompt:false commands.
    prompt: "",
    resolvedArgv: route.resolvedArgv,
    timeout: fields.timeout,
    assignedAt: "2026-09-12T00:00:00.000Z",
    attemptId: "x".repeat(512),
    ...(fields.metadata ? { metadata: fields.metadata } : {}),
    ...(route.providerAccountId ? { providerAccountId: route.providerAccountId } : {}),
    commandId: route.commandId,
    targetIndex: route.targetIndex,
  };
}

/**
 * The actual scheduler independently measures its final frame. This admission
 * pass freezes the selected setup profile and rejects any currently-routable
 * command whose escaped JSON assignment cannot fit the control channel.
 */
export function workspaceAssignmentPayloadError(
  state: ControlPlaneState,
  fields: WorkspaceAssignmentFields,
): string | null {
  const pool = state.workspacePools.get(fields.workspacePoolId);
  const setupProfileId = fields.setupProfileId ?? pool?.defaultSetupProfileId;
  const setupScript =
    fields.workspaceSetupScript ??
    (setupProfileId
      ? pool?.setupProfiles.find((profile) => profile.id === setupProfileId)?.script
      : undefined);
  const frozenFields: WorkspaceAssignmentFields = {
    ...fields,
    ...(setupProfileId ? { setupProfileId } : {}),
    destroyWorkspaceAfter: fields.destroyWorkspaceAfter ?? pool?.destroyWorkspaceAfter ?? false,
  };
  const targets = [fields.target, ...fields.fallbacks];
  for (const [targetIndex, target] of targets.entries()) {
    const routes = workspaceAdmissionRoutes(state, fields.workspacePoolId, target);
    // A provider target can acquire a default command or host-account route
    // after this session is queued. With no route to serialize now, there is
    // no bounded frame to freeze, so admitting it would let a later catalog
    // change turn this already-accepted session into an oversized assignment.
    if (routes.length === 0) {
      return "workspace session has no currently routable assignment";
    }
    let measuredRoute = false;
    for (const route of routes) {
      const command = state.commands.get(route.commandId);
      if (!command) continue;
      measuredRoute = true;
      const resolvedArgv = command.appendPrompt
        ? [...command.argv, ...(command.appendPromptSeparator ? ["--"] : []), fields.prompt]
        : [...command.argv];
      const message = workspaceAssignmentMessage(frozenFields, setupScript, {
        ...route,
        targetIndex,
        resolvedArgv,
      });
      if (Buffer.byteLength(JSON.stringify(message), "utf8") > MAX_WORKSPACE_ASSIGN_BYTES) {
        return `workspace session assignment exceeds ${String(MAX_WORKSPACE_ASSIGN_BYTES)} byte WebSocket limit`;
      }
    }
    if (!measuredRoute) {
      return "workspace session has no currently routable assignment";
    }
  }
  return null;
}

export function workspaceCreatePayloadError(
  state: ControlPlaneState,
  fields: ValidatedFields,
): string | null {
  return fields.workspacePoolId
    ? workspaceAssignmentPayloadError(state, { ...fields, workspacePoolId: fields.workspacePoolId })
    : null;
}

export function validateSessionCreate(
  state: ControlPlaneState,
  body: unknown,
  options: {
    allowScheduleId?: boolean;
    allowReservedConcurrencyId?: boolean;
    allowCustomWebhookConcurrencyId?: boolean;
  } = {},
):
  | {
      ok: true;
      fields: ValidatedFields;
      record: Record<string, unknown>;
      targetDisplayNames: string[];
      scheduleId?: string;
    }
  | { ok: false; error: string; code?: string } {
  if (typeof body !== "object" || body === null) {
    return { ok: false, error: "body must be an object" };
  }
  const record = body as Record<string, unknown>;
  const validated = validateCreateSessionInput(
    {
      repositoryId: record.repositoryId,
      prompt: record.prompt,
      target: record.target,
      fallbacks: record.fallbacks,
      queueTtlSeconds: record.queueTtlSeconds,
      timeout: record.timeout,
      priority: record.priority,
      requiredLabels: record.requiredLabels,
      ref: record.ref,
      concurrencyId: record.concurrencyId,
      metadata: record.metadata,
      type: record.type,
      source: record.source,
      workspacePoolId: record.workspacePoolId,
      setupProfileId: record.setupProfileId,
      destroyWorkspaceAfter: record.destroyWorkspaceAfter,
      setupScript: record.setupScript,
      ...(options.allowReservedConcurrencyId ? { allowReservedConcurrencyId: true } : {}),
    },
    options.allowCustomWebhookConcurrencyId ? { allowCustomWebhookConcurrencyId: true } : {},
  );
  if (!validated.ok) return validated;
  if (validated.value.repositoryId) {
    const admissionFailure = repositoryAdmissionFailure(state, validated.value.repositoryId);
    if (admissionFailure) return admissionFailure;
  } else {
    const pool = state.workspacePools.get(validated.value.workspacePoolId!);
    if (!pool) return { ok: false, error: "workspace pool not found", code: "NOT_FOUND" };
    if (
      validated.value.setupProfileId &&
      !pool.setupProfiles.some((profile) => profile.id === validated.value.setupProfileId)
    ) {
      return { ok: false, error: "workspace setup profile not found", code: "NOT_FOUND" };
    }
  }
  const targets = resolveTargetDisplayNames(
    state,
    validated.value.target,
    validated.value.fallbacks,
  );
  if (!targets.ok) return { ok: false, error: targets.error, code: "VALIDATION_ERROR" };
  const workspacePayloadError = workspaceCreatePayloadError(state, validated.value);
  if (workspacePayloadError) {
    return { ok: false, error: workspacePayloadError, code: "VALIDATION_ERROR" };
  }
  return {
    ok: true,
    fields: validated.value,
    record,
    targetDisplayNames: targets.displayNames,
    ...(options.allowScheduleId && typeof record.scheduleId === "string"
      ? { scheduleId: record.scheduleId }
      : {}),
  };
}

export function buildSessionRecord(
  state: ControlPlaneState,
  prepared: Extract<ReturnType<typeof validateSessionCreate>, { ok: true }>,
  principalId?: string,
): SessionRecord {
  const { fields: v } = prepared;
  const id = state.idFactory();
  const createdAt = state.now();
  const workspacePool = v.workspacePoolId ? state.workspacePools.get(v.workspacePoolId) : undefined;
  const setupProfileId = v.workspacePoolId
    ? (v.setupProfileId ?? workspacePool?.defaultSetupProfileId)
    : undefined;
  const workspaceSetupScript = setupProfileId
    ? workspacePool?.setupProfiles.find((profile) => profile.id === setupProfileId)?.script
    : undefined;
  return {
    id,
    repositoryId: v.repositoryId ?? "",
    ...(v.workspacePoolId ? { workspacePoolId: v.workspacePoolId } : {}),
    ...(setupProfileId ? { setupProfileId } : {}),
    ...(workspaceSetupScript ? { workspaceSetupScript } : {}),
    ...(v.workspacePoolId
      ? {
          destroyWorkspaceAfter:
            v.destroyWorkspaceAfter ??
            state.workspacePools.get(v.workspacePoolId)?.destroyWorkspaceAfter ??
            false,
        }
      : {}),
    prompt: v.prompt,
    target: v.target,
    fallbacks: v.fallbacks,
    targetDisplayNames: prepared.targetDisplayNames,
    queueTtlSeconds: v.queueTtlSeconds,
    queueExpiresAt: new Date(Date.parse(createdAt) + v.queueTtlSeconds * 1000).toISOString(),
    timeout: v.timeout,
    priority: v.priority,
    requiredLabels: v.requiredLabels,
    status: "queued",
    queueShard: Math.abs(hashString(id)) % state.shardCount,
    createdAt,
    ...(v.ref !== undefined ? { ref: v.ref } : {}),
    ...(v.concurrencyId !== undefined ? { concurrencyId: v.concurrencyId } : {}),
    ...(prepared.scheduleId !== undefined ? { scheduleId: prepared.scheduleId } : {}),
    ...(v.metadata !== undefined ? { metadata: v.metadata } : {}),
    ...(principalId ? { principalId } : {}),
    type: v.type,
    source: v.source,
  };
}
